name: Deploy AI Server to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: clairekwak/edison_ai:${{ github.sha }}
          push: true

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull clairekwak/edison_ai:${{ github.sha }}

            # 기존에 실행 중인 컨테이너가 있으면 중지하고 삭제 (없어도 오류가 나지 않도록 || true 추가)
            docker stop edison-ai-server || true
            docker rm edison-ai-server || true

            docker run -d -p 8000:8000 --name edison-ai-server clairekwak/edison_ai:${{ github.sha }}
            
            # 사용하지 않는 오래된 이미지를 삭제
            docker image prune -af
